name: Build

on:
  push:
  pull_request:
  release:
    types:
      - published
      - edited

jobs:
  build-push:
    runs-on: ubuntu-latest
    env:
      DOCKERHUB_USERNAME: gokhlayeh # used in non trustworthy section of the job
      buildx_platforms: linux/amd64
    steps:
      # preparation
      #
      - name: Remove unused packages from disk
        run: |
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /usr/share/dotnet
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: all
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Cache Docker layers
        uses: actions/cache@v2
        env:
          cache-name: docker-cache
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('./docker/Dockerfile') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      #
      # push image (if trusted commit)
      #
      - name: Login to DockerHub
        if: ${{ github.event_name == 'release' || (github.event_name == 'push' && github.ref == 'refs/heads/master') }}
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push unstable
        if: ${{ github.event_name == 'release' || (github.event_name == 'push' && github.ref == 'refs/heads/master') }}
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./docker
          file: ./docker/Dockerfile
          platforms: ${{ env.buildx_platforms }}
          load: false
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/latex:unstable
      - name: Determine release tag name
        if: ${{ github.event_name == 'release' }}
        id: vars
        run: echo ::set-output name=tag::$(echo ${GITHUB_REF:10})
      - name: Build and push release
        if: ${{ github.event_name == 'release' }}
        uses: docker/build-push-action@v2
        with:
          context: ./docker
          file: ./docker/Dockerfile
          platforms: ${{ env.buildx_platforms }}
          load: false
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/latex:${{steps.vars.outputs.tag}},
            ${{ secrets.DOCKERHUB_USERNAME }}/latex:latest
      - name: Update Docker Hub description
        if: ${{ github.event_name == 'release' || (github.event_name == 'push' && github.ref == 'refs/heads/master') }}
        uses: peter-evans/dockerhub-description@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          readme-filepath: README.md
          repository: ${{ secrets.DOCKERHUB_USERNAME }}/latex
